[settings]
# LLM for the insertion
insertion_llm = gpt-4.1

# Retriever for the selection
retriever = hybrid_sbert_1024_tfidf

# Path to the catalogue file
catalogue = /home/kilo/BLM_AI_Classifier/catalogues/catalogue_01.csv

# output length selection
output_length = 10

# language selection
language = ita