[settings]
# LLM for the insertion
insertion_llm = gpt-4o

# Retriever for the selection
retriever = sbert_1024

# Path to the catalogue file
catalogue = /home/kilo/BLM_AI_Classifier/catalogues/catalogue_01.csv

# output length selection
output_length = 10